image: node:8.9

pages:
  stage: deploy
  script:
    - tar -zcvf ./public.tar.gz ./*
    - mkdir ./public
    - tar -zxvf ./public.tar.gz -C ./public
  artifacts:
    paths:
      - public
  only:
    - master