name: snowdreams1006.tech

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Build Blog
      run: |
        npm install -g gitbook-cli
        gitbook install
        gitbook build 
    - name: Upload Blog
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
      with:
        source: ${{ secrets.SOURCE }}
        target: ${{ secrets.TARGET }}
    - name: Deploy Blog
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          mv ${{ secrets.SOURCE }} ${{ secrets.TARGET }}
          rm -rf ${{ secrets.SOURCE }}