name: blog

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "8.x"
    - name: Build blog with gitbook
      run: |
        npm install -g gitbook-cli
        gitbook install
        gitbook build 
    - name: Upload blog with scp
      uses: appleboy/scp-action@v0.1.1
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
      with:
        source: _book
        target: ~/blog
        rm: true
        strip_components: 1
    - name: Deploy blog with ssh
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker restart blog
    - uses: manyuanrong/setup-ossutil@v1.0
      with:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        access-key-id: ${{ secrets.ALI_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ALI_ACCESS_KEY_SECRET }}
    - name: Upload files to aliyun oss
      run: ossutil cp -rf ./_book oss://snowdreams1006/