name: snowdreams1006.tech

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"  
        registry-url: "https://registry.npm.taobao.org"
    - name: gitbook build 
      run: |
        npm install -g gitbook-cli
        gitbook install
        gitbook build 
    - name: deploy aliyun-oss
    - uses: manyuanrong/setup-ossutil@v1.0
      with:
        endpoint: "oss-cn-hongkong.aliyuncs.com"
        access-key-id: ${{ secrets.ALI_OSS_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ALI_OSS_ACCESS_KEY_SECRET }}
      run: ossutil cp -rf _book oss://snowdreams1006/ 